//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public Chapter()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Content { get; set; }
        public double Price { get; set; }
        public int Publication_Id { get; set; }
    
        public virtual Publication Publication { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
