//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Genre1 = new HashSet<Genre>();
            this.Publication = new HashSet<Publication>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentGenre_Id { get; set; }
    
        public virtual ICollection<Genre> Genre1 { get; set; }
        public virtual Genre Genre2 { get; set; }
        public virtual ICollection<Publication> Publication { get; set; }
    }
}
