//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public Publication()
        {
            this.Chapter = new HashSet<Chapter>();
            this.PublicationGenre = new HashSet<PublicationGenre>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int Category_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Chapter> Chapter { get; set; }
        public virtual ICollection<PublicationGenre> PublicationGenre { get; set; }
        public virtual User User { get; set; }
    }
}
