//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationGenre
    {
        public int Publication_Id { get; set; }
        public int Genre_Id { get; set; }
        public int PublicationGenre_Id { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
