//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Publication = new HashSet<Publication>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthdate { get; set; }
        public double Balance { get; set; }
    
        public virtual ICollection<Publication> Publication { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
